import os.path
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build

# IMPORTANT: We need all 3 Scopes: creating forms, editing questions, and fetching results.
SCOPES = [
    'https://www.googleapis.com/auth/forms.body',
    'https://www.googleapis.com/auth/forms.responses.readonly',
    'https://www.googleapis.com/auth/drive.file'
]

from dotenv import load_dotenv
load_dotenv()

# The OAuth credentials you initially provided
client_config = {
    "installed": {
        "client_id": os.getenv("GOOGLE_OAUTH_CLIENT_ID"),
        "project_id": os.getenv("GOOGLE_PROJECT_ID", "formapi-453516"),
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_secret": os.getenv("GOOGLE_OAUTH_CLIENT_SECRET"),
        "redirect_uris": ["http://localhost:8080/"]
    }
}

TOKEN_FILE = 'Agent/token.json'

def get_authenticated_service():
    """
    Shows basic usage of the Forms API.
    Prints the Title of the target Google Form.
    """
    creds = None
    
    # 1. Check if we already have a valid token.json from a previous run
    if os.path.exists(TOKEN_FILE):
        creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)
        
    # 2. If there are no (valid) credentials available, let the user log in ONCE.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            print("Token expired, refreshing automatically...")
            creds.refresh(Request())
        else:
            print("No valid token found. Initiating One-Time Browser Authorization...")
            flow = InstalledAppFlow.from_client_config(client_config, SCOPES)
            creds = flow.run_local_server(port=8080, prompt='consent')
            
        # Save the credentials for the next run
        with open(TOKEN_FILE, 'w') as token:
            token.write(creds.to_json())
            print(f"✅ Success! Generated permanent Refresh Token and saved to {TOKEN_FILE}.")
            print("From now on, your Python backend can create forms in the background without browser popups!")

    return build('forms', 'v1', credentials=creds)

def test_auto_creation_and_modification():
    service = get_authenticated_service()

    # --- A. CREATE A NEW BLANK FORM ---
    print("\n1. Creating a brand new Form...")
    NEW_FORM = {
        "info": {
            "title": "My Awesome Automated Form v2",
            "documentTitle": "Generated by Python Script"
        }
    }
    created_form = service.forms().create(body=NEW_FORM).execute()
    form_id = created_form.get('formId')
    responder_url = created_form.get('responderUri')
    
    print(f"   -> Form created with ID: {form_id}")
    print(f"   -> Give this URL to users: {responder_url}")


    # --- B. ADD DYNAMIC QUESTIONS TO THE FORM ---
    print("\n2. Injecting questions into the newly created Form...")
    update_request = {
        "requests": [
            {
                "createItem": {
                    "item": {
                        "title": "What text prompt rules did you just learn?",
                        "questionItem": {
                           "question": {
                               "required": True,
                               "textQuestion": { "paragraph": True }
                           }
                        }
                    },
                    "location": { "index": 0 }
                }
            }
        ]
    }
    
    # Send the updates to Google Forms API
    service.forms().batchUpdate(formId=form_id, body=update_request).execute()
    print("   -> Questions successfully injected!")

if __name__ == '__main__':
    test_auto_creation_and_modification()
